openapi: 3.0.1
info:
  title: API-AJNA
  description: API para acesso de outras aplicações a dados do AJNA
  version: "1.0a"
servers:
  - url: /ajnaapi/api
paths:
  /login:
    post:
      summary: retorna token JWT
      operationId: authentication.generate_token
      requestBody:
        description: Usuario e Senha
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthenticationJson'
      responses:
        '200':
          description: JWT token
          content:
            'text/plain':
              schema:
                type: string
  /secret:
    get:
      summary: Return secret string
      operationId: authentication.get_secret
      responses:
        '200':
          description: secret response
          content:
            'text/plain':
              schema:
                type: string
      security:
        - jwt: ['secret']
  /grid_data:
    post:
      requestBody:
        description: Lista de eventos maiores que um ID ou Data
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: aplication/json
                  description: Campos a retornar - padrão MongoDB
                  required: true
                recinto:
                  type: aplication/json
                  description: Campos a retornar - padrão MongoDB
                  required: true
      responses:
        200:
          description:
          content:
            image/jpeg:
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /image/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: id da imagem do escaneamento no banco de dados AJNA
          required: true
          schema:
            type: string
      responses:
        200:
          description:
          content:
            image/jpeg:
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /summary_aniita/{ce_mercante}:
    get:
      parameters:
        - name: ce_mercante
          in: path
          description: número do conhecimento de transporte NIC CE Mercante
          required: true
          schema:
            type: string
      responses:
        200:
          description: Lista de contêineres do CE, algumas informações do sistema Mercante, id das imagens do CE
          content:
            aplication/json:
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /conhecimentos/{numeroCEmercante}:
    get:
      parameters:
        - name: numeroCEmercante
          in: path
          description: Numero do CE Mercante no sistema original
          required: true
          schema:
            type: string
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conhecimentos'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /conhecimentos/new/{datamodificacao}:
    get:
      parameters:
        - name: datamodificacao
          in: path
          description: Data inicial de pesquisa
          required: true
          schema:
            type: string
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conhecimentos'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /conhecimentos:
    get:
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conhecimentos'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /manifestos/{numero}:
    get:
      parameters:
        - name: numero
          in: path
          description: Numero do Manifesto no sistema original
          required: true
          schema:
            type: string
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/manifestos'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /manifestos/new/{datamodificacao}:
    get:
      parameters:
        - name: datamodificacao
          in: path
          description: Data inicial de pesquisa
          required: true
          schema:
            type: string
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/manifestos'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /manifestos:
    get:
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/manifestos'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /itens/{conhecimento}:
    get:
      parameters:
        - name: numero
          in: path
          description: Numero do Manifesto no sistema original
          required: true
          schema:
            type: string
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/itens'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /itens/{conhecimento}/{sequencial}:
    get:
      parameters:
        - name: numero
          in: path
          description: Numero do Manifesto no sistema original
          required: true
          schema:
            type: string
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/itens'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /itens/new/{datamodificacao}:
    get:
      parameters:
        - name: datamodificacao
          in: path
          description: Data inicial de pesquisa
          required: true
          schema:
            type: string
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/itens'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /itens:
    get:
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/itens'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /NCMitem/{conhecimento}:
    get:
      parameters:
        - name: numero
          in: path
          description: Numero do Manifesto no sistema original
          required: true
          schema:
            type: string
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NCMitem'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /NCMitem/{conhecimento}/{sequencial}:
    get:
      parameters:
        - name: numero
          in: path
          description: Numero do Manifesto no sistema original
          required: true
          schema:
            type: string
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NCMitem'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /NCMitem/new/{datamodificacao}:
    get:
      parameters:
        - name: datamodificacao
          in: path
          description: Data inicial de pesquisa
          required: true
          schema:
            type: string
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NCMitem'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /NCMitem:
    get:
      responses:
        200:
          description: Conhecimento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NCMitem'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /conteineresVazios/{manifesto}:
    get:
      parameters:
        - name: manifesto
          in: path
          description: Numero do Manifesto no sistema original
          required: true
          schema:
            type: string
      responses:
        200:
          description: Lista de Conteineres Vazios
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conteineresVazios'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /conteineresVazios/new/{datamodificacao}:
    get:
      parameters:
        - name: datamodificacao
          in: path
          description: Data inicial de pesquisa
          required: true
          schema:
            type: string
      responses:
        200:
          description: Lista de Conteineres Vazios
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conteineresVazios'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
  /conteineresVazios:
    get:
      responses:
        200:
          description: Lista de Conteineres Vazios
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/conteineresVazios'
        400:
          description: Erro
          content: {}
        404:
          description: Não encontrado para filtro atual.
          content: {}
      security:
        - jwt: ['secret']
components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: authentication.decode_token
  schemas:
    AuthenticationJson:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    conhecimentos:
      type: object
      properties:
        codigoEmpresaNavegacao:
          type: string
        codigoTerminalCarregamento:
          type: string
        consignatario:
          type: string
        cubagem:
          type: string
        dataAtualizacao:
          type: string
        dataEmissao:
          type: string
        descricao:
          type: string
        embarcador:
          type: string
        horaAtualizacao:
          type: string
        indicadorShipsConvenience:
          type: string
        manifestoCE:
          type: string
        numeroCEMaster:
          type: string
        numeroCEmercante:
          type: string
        paisDestinoFinalMercante:
          type: string
        portoDestFinal:
          type: string
        portoOrigemCarga:
          type: string
        tipoBLConhecimento:
          type: string
        tipoTrafego:
          type: string
    manifestos:
      type: object
      properties:
        numero:
          type: string
    itens:
      type: object
      properties:
        numeroCEmercante:
          type: string
        numeroSequencialItemCarga:
          type: string
        codigoConteiner:
          type: string
        NCM:
          type: string
    NCMitem:
      type: object
      properties:
        numeroCEmercante:
          type: string
        numeroSequencialItemCarga:
          type: string
        identicacaoNCM:
          type: string
    conteineresVazios:
      type: object
      properties:
        manifesto:
          type: string
        idConteinerVazio:
          type: string
